// ROUND 298 -- gather the validated pairs into src/data/fusions/<essenceId>.js.
//   node tools/fusions/assemble.mjs        (every essence with authored pairs)
// Only pairs that pass the validator are shipped; the rest are reported.
import fs from 'fs'; import path from 'path'; import { fileURLToPath } from 'url';
const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../..');
const { checkPair } = await import('./validate.mjs');
const OUT = path.join(HERE, 'out');
const DEST = path.join(ROOT, 'src/data/fusions');
fs.mkdirSync(DEST, { recursive: true });
const summary = { essences: 0, pairs: 0, fusions: 0, rejected: [] };
for (const ess of (fs.existsSync(OUT) ? fs.readdirSync(OUT) : []).sort()) {
  const dir = path.join(OUT, ess);
  if (!fs.statSync(dir).isDirectory()) continue;
  const table = {};
  const seen = new Set();
  for (const f of fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort()) {
    const stone = f.replace(/\.json$/, '');
    let doc; try { doc = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')); } catch (e) { summary.rejected.push(`${ess}/${stone}: unreadable`); continue; }
    const errs = checkPair(doc, ess, stone);
    const dup = (doc.fusions || []).find(x => seen.has(String(x.name).toLowerCase()));
    if (errs.length || dup) { summary.rejected.push(`${ess}/${stone}: ${dup ? 'duplicate name ' + dup.name : errs[0]}`); continue; }
    for (const x of doc.fusions) seen.add(String(x.name).toLowerCase());
    table[stone] = doc.fusions;
    summary.pairs++; summary.fusions += doc.fusions.length;
  }
  if (!Object.keys(table).length) continue;
  summary.essences++;
  fs.writeFileSync(path.join(DEST, `${ess}.js`),
    `// Hand-authored fusions for ${ess} (round 298+). Generated by tools/fusions/assemble.mjs from tools/fusions/out/${ess}/; edit those, not this.\nexport default ${JSON.stringify(table)};\n`);
}
const have = fs.readdirSync(DEST).filter(f => f.endsWith('.js') && f !== 'index.js').map(f => f.replace(/\.js$/, '')).sort();
fs.writeFileSync(path.join(DEST, 'index.js'), `// Generated by tools/fusions/assemble.mjs: the essences that have hand-authored fusions.\nexport const FUSION_ESSENCES = ${JSON.stringify(have)};\n`);
console.log(JSON.stringify({ ...summary, rejected: summary.rejected.slice(0, 40), rejectedCount: summary.rejected.length }, null, 1));
