// node tools/fusions/status.mjs [--next N] [--json]
// Where the authoring run stands, from what is on disk, and what to do next.
// Writes tools/fusions/PROGRESS.md.
import fs from 'fs'; import path from 'path'; import { fileURLToPath } from 'url';
const HERE = path.dirname(fileURLToPath(import.meta.url));
const C = JSON.parse(fs.readFileSync(path.join(HERE, 'chunks.json'), 'utf8'));
const has = (id, st) => fs.existsSync(path.join(HERE, 'done', `${id}.${st}`));
const pairFiles = (c) => c.stones.filter(s => fs.existsSync(path.join(HERE, 'out', c.essence, `${s}.json`))).length;
const rows = C.map((c, i) => ({ i, id: c.id, essence: c.essence, pairs: c.stones.length, written: pairFiles(c), authored: has(c.id, 'authored'), reviewed: has(c.id, 'reviewed') }));
const sum = (f) => rows.filter(f).reduce((n, r) => n + r.pairs, 0);
const totalPairs = rows.reduce((n, r) => n + r.pairs, 0);
const authored = rows.filter(r => r.authored), reviewed = rows.filter(r => r.reviewed);
const toReview = rows.filter(r => r.authored && !r.reviewed);
const toAuthor = rows.filter(r => !r.authored);
const nextN = Number((process.argv.find(a => /^\d+$/.test(a))) || 60);
const next = [...toReview.map(r => `R:${r.id}`), ...toAuthor.map(r => r.id)].slice(0, nextN);
if (process.argv.includes('--json')) { process.stdout.write(JSON.stringify(next)); process.exit(0); }
const pct = (a, b) => `${(a / b * 100).toFixed(1)}%`;
const essDone = new Set(reviewed.map(r => r.essence)).size;
const md = `# Fusion authoring: progress

Generated by \`node tools/fusions/status.mjs\` from what is on disk. Regenerate it; do not edit it.

| | Chunks | Pairs | Share of all pairs |
|---|---|---|---|
| Total (148 essences x 191 stones, less canon pairs) | ${rows.length} | ${totalPairs} | 100% |
| Written and passing the validator | ${authored.length} | ${sum(r => r.authored)} | ${pct(sum(r => r.authored), totalPairs)} |
| ...of those, reviewed | ${reviewed.length} | ${sum(r => r.reviewed)} | ${pct(sum(r => r.reviewed), totalPairs)} |
| Written, waiting for review | ${toReview.length} | ${sum(r => r.authored && !r.reviewed)} | ${pct(sum(r => r.authored && !r.reviewed), totalPairs)} |
| Not started | ${toAuthor.length} | ${sum(r => !r.authored)} | ${pct(sum(r => !r.authored), totalPairs)} |

Each pair holds 4 fusions (attack, attack, active, passive). Chunks are in priority order: the pairs a player is most likely to hold come first (drop weights of the essence and the stone).

## Next up (priority order)

${next.slice(0, 40).map(x => `- ${x.startsWith('R:') ? `review ${x.slice(2)}` : `author + review ${x}`}`).join('\n') || '- nothing: the run is complete'}

## How to resume

1. \`node tools/fusions/status.mjs\` (this file) shows where the run stands.
2. \`node tools/fusions/status.mjs --json 120\` prints the next 120 work items. Split that list across up to six runs of the workflow \`tools/fusions/wave.workflow.js\` (each run works two chunks at a time). An item \`R:<chunk>\` is review only.
3. When runs finish or stop: \`node tools/fusions/assemble.mjs\` ships every pair that passes the validator into \`src/data/fusions/\`, then commit.
4. A chunk only counts once its agent has run \`mark.mjs\`; a run cut off mid-chunk is simply done again.

## Written and reviewed, by essence

${[...new Set(rows.map(r => r.essence))].map(e => { const rs = rows.filter(r => r.essence === e); const a = rs.filter(r => r.authored).reduce((n, r) => n + r.pairs, 0); const v = rs.filter(r => r.reviewed).reduce((n, r) => n + r.pairs, 0); const t = rs.reduce((n, r) => n + r.pairs, 0); return a ? `- ${e}: ${a} of ${t} pairs written, ${v} reviewed` : null; }).filter(Boolean).join('\n') || '- none yet'}
`;
fs.writeFileSync(path.join(HERE, 'PROGRESS.md'), md);
console.log(`chunks ${rows.length}: authored ${authored.length}, reviewed ${reviewed.length}, to review ${toReview.length}, to author ${toAuthor.length} | pairs written ${sum(r => r.authored)}/${totalPairs} (${pct(sum(r => r.authored), totalPairs)}), reviewed ${sum(r => r.reviewed)} | essences with a reviewed chunk: ${essDone}`);
